# Generated by Django 6.0.4 on 2026-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_customer_city_customer_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
