# Generated by Django 6.0.4 on 2026-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_product_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='gallery/%Y/%m/%d'),
        ),
    ]
